
server:
  port: 8082
  servlet:
    context-path: /api
    
spring:
  application:
    name: school_class
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/school_class?allowPublicKeyRetrieval=true&sslMode=DISABLED&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  
 